### ISSUE TITLE
MWindowLib 1.3 Nuget package broken

### ISSUE THREAD

**Issue by dgosbell** [Dirkster99/MLib#3]
Something changed in the nuget packages for the 1.3 release. All the packages now have the library name as the Author (so it says "Mlib by Mlib" instead of "Dirkster.Mlib by Dirke Bahle" ) so they are showing as a completely separate package from the prior releases. 

And MWindowLib will not install at all as it says it has a dependency on MWindowInterfacesLib (>= 1.3.0) which does not appear to be published on nugget.

**Comment by Dirkster99** [comment]
Hi Darren,

thanks for the hint I somehow managed to miss these problems when I converted the projects to multitarget NetCore and .Net.

The first problem was easy to fix since there was simply a **PackageId** tag missing :-( the second problem about the **MWindowInterfacesLib** being missing in **MWindowLib** seems to be a 'known problem' with the new csproj file format and nuget package build:

https://stackoverflow.com/questions/44976879/msbuild-multiple-dll-in-a-single-nuget-package

I have tried various solutions to resolve this but could not find one that works for this project - so, I went back to using Nuget.exe with .nuspec file to generate the MWindowLib nuget package version 1.3.0.2 which should resolve this issue.

Can you confirm this to work as expected?

**Comment by dgosbell** [comment]
Thanks Dirke, that fixed the issue. The new updates now appear aligned with the earlier ones and the dependency on MWindowInterfacesLib is gone.

![image](https://user-images.githubusercontent.com/8241830/72936942-535d7080-3dbc-11ea-80e0-351f268aef42.png)
